// <auto-generated />
using JapaneseStudyApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JapaneseStudyApi.Migrations
{
    [DbContext(typeof(JapaneseStudyContext))]
    partial class JapaneseStudyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("JapaneseStudyApi.Model.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnMeaning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JpWord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pronunciation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThMeaning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
